account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'account'

urlpatterns = [
    path('login', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('signup', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('donadona.urls')),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

donadona/urls.py
from django.urls import path
from . import views

app_name = 'donadona'

urlpatterns = [
    path('', views.main, name='main'),
    path('help/list', views.helpList, name='list'),  # 도움 목록
    path('help/request', views.helpRequest, name='request'),  # 도움 요청
    path('help/<int:help_id>', views.help, name='help'),  # 도움 주기
    path('resolution/<int:help_id>', views.resolution, name='resolution'),  # 도움 해결

    path('manual', views.manual, name='manual'),
    path('ranking', views.ranking, name='ranking'),

    path('mypage', views.mypage, name='mypage'),
    path('mypage/help/list', views.mypageHelp, name='myhelp'),
    path('mypage/info', views.mypageInfo, name='myinfo'),
    path('mypage/info/<str:obj>/<int:pk>', views.mypageObj, name='myobj'),

    path('info', views.userInfo, name='info'),
    path('info/day', views.userDay, name='day'),
    path('info/address', views.userAddress, name='address'),
    path('info/ability', views.userAbility, name='ability'),
]

donadona/forms.py
from django import forms
from donadona.models import *


DAY_CHOICE = [
        ('월요일', '월요일'),
        ('화요일', '화요일'),
        ('수요일', '수요일'),
        ('목요일', '목요일'),
        ('금요일', '금요일'),
        ('토요일 ', '토요일'),
        ('일요일 ', '일요일'),
    ]

CITY_CHOICE = [
    ('서울특별시', '서울특별시'),
    ('경기도', '경기도'),
    ('강원도', '강원도'),
    ('충청북도', '충청북도'),
    ('충청남도', '충청남도'),
    ('전라북도 ', '전라북도'),
    ('전라남도 ', '전라남도'),
    ('경상북도', '경상북도'),
    ('경상남도', '경상남도'),
    ('부산광역시', '부산광역시'),
    ('인천광역시', '인천광역시'),
    ('대구광역시', '대구광역시'),
    ('대전광역시 ', '대전광역시'),
    ('광주광역시 ', '광주광역시'),
    ('울산광역시', '울산광역시'),
    ('세종특별자치시', '세종특별자치시'),
    ('제주특별자치도', '제주특별자치도'),
]


ABLE_CHOICE = [
    ('생활', '생활'),
    ('환경', '환경'),
    ('식사', '식사'),
    ('동행', '동행'),
    ('안전', '안전'),
    ('운동', '운동'),
    ('의료', '의료'),
    ('상담', '상담'),
    ('문화', '문화'),
    ('교육', '교육'),
    ('정서', '정서'),
    ('취미', '취미'),
    ('외국어', '외국어'),
    ('IT', 'IT'),
]


class UserDayForm(forms.Form):
    day_week = forms.ChoiceField(choices=DAY_CHOICE)
    start_time = forms.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(24)])
    end_time = forms.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(24)])

    fields = ['day_week', 'start_time', 'end_time']


class UserAddressForm(forms.Form):
    city = forms.ChoiceField(choices=CITY_CHOICE)
    si_gun_gu = forms.CharField(max_length=20)
    addr_detail = forms.CharField(max_length=100)

    fields = ['city', 'si_gun_gu', 'addr_detail']


class UserAbilityForm(forms.Form):
    able_category = forms.ChoiceField(choices=ABLE_CHOICE)
    able_detail = forms.CharField(max_length=100)

    fields = ['able_category', 'able_detail']


class HelpResolutionForm(forms.Form):
    helper = forms.CharField(max_length=20)
    time = forms.IntegerField()

    fields = ['helper', 'time']


class HelpRequestForm(forms.Form):
    title = forms.CharField(max_length=20)
    content = forms.CharField(max_length=1000)

    hour = forms.IntegerField()
    date = forms.DateField()
    time = forms.TimeField()

    city = forms.ChoiceField(choices=CITY_CHOICE)
    si_gun_gu = forms.CharField(max_length=20)
    addr_detail = forms.CharField(max_length=100)

    able_category = forms.ChoiceField(choices=ABLE_CHOICE)
    able_detail = forms.CharField(max_length=100)

    fields = ['title', 'content',
              'hour', 'date', 'time',
              'city', 'si_gun_gu', 'addr_detail',
              'able_category', 'able_detail']

donadona/views.py
import json

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from datetime import datetime, date
import hashlib
import hmac
import base64
import requests
import time
from decouple import config

timestamp = int(time.time() * 1000)
timestamp = str(timestamp)
access_key = config('SENS_ACCESS_KEY')
url = "https://sens.apigw.ntruss.com"
uri = "/sms/v2/services/" + config('SENS_SERVICE_ID') + "/messages"


def make_signature():
    secret_key = config('SENS_SECRET_KEY')
    secret_key = bytes(secret_key, 'UTF-8')

    method = "POST"

    message = method + " " + uri + "\n" + timestamp + "\n" + access_key
    message = bytes(message, 'UTF-8')
    signingKey = base64.b64encode(hmac.new(secret_key, message, digestmod=hashlib.sha256).digest())
    return signingKey


def day_week_calc(date):
    days = ['월요일', '화요일', '수요일', '목요일', '금요일', '토요일', '일요일']
    day = date.weekday()
    return days[day]


def main(request):
    return render(request, 'donadona/main.html')


def ranking(request):
    users = User.objects.order_by('-hours')
    context = {'users': users}
    return render(request, 'donadona/ranking.html', context)


def helpList(request):
    help_list = Post.objects.all()
    context = {'help_list': help_list}
    return render(request, 'donadona/help_list.html', context)


@login_required(login_url='account:login')
def helpRequest(request):
    if request.method == 'POST':
        form = HelpRequestForm(request.POST)
        if form.is_valid():
            title = request.POST['title']
            content = request.POST['content']
            hour = request.POST['hour']

            help_date = request.POST['date']
            dates = help_date.split('-')
            year = int(dates[0])
            month = int(dates[1])
            day = int(dates[2])
            help_day_week = day_week_calc(date(year, month, day))

            help_time = request.POST['time']
            hour_minute = help_time.split(':')
            help_start_time = int(hour_minute[0])

            help_city = request.POST['city']
            help_si_gun_gu = request.POST['si_gun_gu']
            help_addr_detail = request.POST['addr_detail']
            help_able_category = request.POST['able_category']
            help_able_detail = request.POST['able_detail']

            Post.objects.create(
                author=request.user, title=title, content=content,
                hour=hour, help_day_week=help_day_week, help_date=help_date, help_time=help_time,
                help_city=help_city, help_si_gun_gu=help_si_gun_gu, help_addr_detail=help_addr_detail,
                help_able_category=help_able_category, help_able_detail=help_able_detail
            )

            users = User.objects.filter(alarm=True)
            helper_phone = []
            for user in users:
                if request.user != user:
                    try:
                        addr = Address.objects.get(user=user, city=help_city)
                        AddressDetail.objects.filter(address=addr, si_gun_gu=help_si_gun_gu)
                        Ability.objects.get(user=user, able_category=help_able_category)
                        day = Day.objects.get(user=user, day_week=help_day_week)
                        times = Time.objects.filter(day=day)
                        for t in times:
                            if t.start_time <= help_start_time and t.end_time >= (help_start_time + int(hour)):
                                helper_phone.append(user.phone)
                    except:
                        pass

            for phone_num in helper_phone:
                header = {
                    "Content-Type": "application/json; charset=utf-8",
                    "x-ncp-apigw-timestamp": timestamp,
                    "x-ncp-iam-access-key": config('SENS_ACCESS_KEY'),
                    "x-ncp-apigw-signature-v2": make_signature(),
                }

                data = {
                    "type": "SMS",
                    "from": config('SENS_PHONE_NUM'),
                    "content": "[도나도나]",  # max 80byte, 기본 메시지 제목
                    "messages": [
                        {
                            "to": phone_num,  # 수신 번호
                            "content": str(request.user.nickname) + "님께서 도움을 요청했어요!\n"  # 개별 메시지 내용
                                       + "[요청] " + title + "\n"
                                       + "[날짜] " + help_date
                        }
                    ]
                }
                res = requests.post(url + uri, headers=header, data=json.dumps(data))
            return redirect('donadona:list')
    else:
        form = HelpRequestForm()
    context = {'form': form}
    return render(request, 'donadona/help_request_form.html', context)


@login_required(login_url='account:login')
def help(request, help_id):  # 도움 주기

    post = Post.objects.get(pk=help_id)
    phone_num = post.author.phone

    header = {
        "Content-Type": "application/json; charset=utf-8",
        "x-ncp-apigw-timestamp": timestamp,
        "x-ncp-iam-access-key": config('SENS_ACCESS_KEY'),
        "x-ncp-apigw-signature-v2": make_signature(),
    }

    data = {
        "type": "SMS",
        "from": config('SENS_PHONE_NUM'),
        "content": "[도나도나]",  # max 80byte, 기본 메시지 제목
        "messages": [
            {
                "to": phone_num,  # 수신 번호
                # LMS 용
                # "content": str(request.user.nickname) + "님께서 도와주신대요!\n"
                #            + "[번호] " + str(request.user.phone) + "\n"
                #            + "[아이디] " + str(request.user)
                #
                #            + "\n\n" + str(post.help_able_detail) + "에 관련된 [ " + str(post.title) + " ] 를 도와주실 수 있으시대요.\n"
                #            + "연락을 통해 도움을 받아보세요 :)\n\n"
                #            + "※ 도움을 받으신 후, 해결되었다면 게시글 하단의 \"도움 해결\" 버튼을 눌러주세요.\n"
                #            + "※ \"도움 해결\" 버튼을 누르지 않으시거나 허위사실을 기재하시면 서비스를 이용하시는 데에 불이익이 발생할 수 있습니다."

                # SMS 용
                "content": str(request.user.nickname) + "님께서 도와주신대요\n"
                           + str(request.user.phone) + "로 연락해보세요!\n"
                           + "ID: " + str(request.user)
            }
        ]
    }
    res = requests.post(url + uri, headers=header, data=json.dumps(data))
    return redirect('donadona:list')  # Send SMS


@login_required(login_url='account:login')
def resolution(request, help_id):
    if request.method == 'POST':
        form = HelpResolutionForm(request.POST)
        if form.is_valid():
            helper = request.POST['helper']
            time = request.POST['time']

            try:
                user = User.objects.get(username=helper)
            except:
                return render(request, 'error.html')

            user.hours = user.hours + int(time)
            user.point = user.point + int(time) * 500
            user.save()

            post = Post.objects.get(pk=help_id)
            post.solved_flag = True
            post.helper = user
            post.save()
            return redirect('donadona:list')
    else:
        form = HelpResolutionForm()
    context = {'form': form}
    return render(request, 'donadona/helper_form.html', context)


def manual(request):
    return render(request, 'donadona/manual.html')


@login_required(login_url='account:login')
def mypage(request):
    return render(request, 'donadona/mypage.html')


@login_required(login_url='account:login')
def mypageHelp(request):
    posts = Post.objects.filter(author=request.user)
    helper = Post.objects.filter(helper=request.user)
    context = {'posts': posts, 'helper': helper}
    return render(request, 'donadona/mypage_help.html', context)


@login_required(login_url='account:login')
def mypageInfo(request):
    times = Time.objects.filter(day__user=request.user)
    addresses = AddressDetail.objects.filter(address__user=request.user)
    abilities = AbilityDetail.objects.filter(ability__user=request.user)
    context = {'times': times, 'addresses': addresses, 'abilities': abilities}
    return render(request, 'donadona/mypage_info.html', context)


@login_required(login_url='account:login')
def mypageObj(request, obj, pk):
    if obj == 'time':
        target = Time.objects.get(pk=pk)
    elif obj == 'address':
        target = AddressDetail.objects.get(pk=pk)
    else:
        target = AbilityDetail.objects.get(pk=pk)
    target.delete()
    return redirect('donadona:myinfo')


@login_required(login_url='account:login')
def userInfo(request):
    return render(request, 'donadona/user_info.html')


@login_required(login_url='account:login')
def userDay(request):
    if request.method == 'POST':
        form = UserDayForm(request.POST)
        if form.is_valid():
            day_week = request.POST['day_week']
            start_time = request.POST['start_time']
            end_time = request.POST['end_time']
            user = request.user

            user_day = Day.objects.get_or_create(user=user, day_week=day_week)
            Time.objects.create(day=user_day[0], start_time=start_time, end_time=end_time)
            return redirect('donadona:info')
    else:
        form = UserDayForm()
    context = {'form': form}
    return render(request, 'donadona/user_day_form.html', context)


@login_required(login_url='account:login')
def userAddress(request):
    if request.method == 'POST':
        form = UserAddressForm(request.POST)
        if form.is_valid():
            city = request.POST['city']
            si_gun_gu = request.POST['si_gun_gu']
            addr_detail = request.POST['addr_detail']
            user = request.user

            user_addr = Address.objects.get_or_create(user=user, city=city)
            AddressDetail.objects.create(address=user_addr[0], si_gun_gu=si_gun_gu, addr_detail=addr_detail)
            return redirect('donadona:info')
    else:
        form = UserAddressForm()

templates/donadona/help_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Portfolio Grid-->
        <section class="page-section bg-light" id="portfolio">
            <div class="container">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">도움 목록</h2>
                    <h3 class="section-subheading text-muted">These are things that need help.</h3>
                </div>
                <div class="row">
                    <div class="col-lg-4 col-sm-6 mb-4">
                    {% for help in help_list %}
                    {% if help.solved_flag == False %}
                        <!-- Portfolio item 1-->
                        <div class="portfolio-item">
                            <a class="portfolio-link" data-bs-toggle="modal" href="#help{{help.id}}">
                                <div class="portfolio-hover">
                                    <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>
                                </div>
                                <img class="img-fluid" src='{% static "assets/img/portfolio/1.jpg" %}' alt="..." />
                            </a>
                            <div class="portfolio-caption">
                                <div class="portfolio-caption-heading">{{help.title}}</div>
                                <div class="portfolio-caption-subheading text-muted"><Strong>{{help.help_city}} {{help.help_si_gun_gu}}</Strong><br>{{help.help_able_category}} 분야의 {{help.help_able_detail}} 관련</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-6 mb-4">
                    <!-- Portfolio Modals-->
                    <!-- Portfolio item 1 modal popup-->
                    <div class="portfolio-modal modal fade" id="help{{help.id}}" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="close-modal" data-bs-dismiss="modal"><img src='{% static "assets/img/close-icon.svg" %}' alt="Close modal" /></div>
                                <div class="container">
                                    <div class="row justify-content-center">
                                        <div class="col-lg-8">
                                            <div class="modal-body">
                                                <!-- Project details-->
                                                <h2 class="text-uppercase">{{help.title}}</h2>
                                                <p class="item-intro text-muted"><Strong>{{help.help_city}} {{help.help_si_gun_gu}}</Strong>
                                                <br> {{help.help_able_category}} 분야의 {{help.help_able_detail}} 관련</p>
                                                <!-- <img class="img-fluid d-block mx-auto" src='{% static "assets/img/portfolio/1.jpg" %}' alt="..." /> -->
                                                <p>{{help.content}}</p>
                                                <ul class="list-inline">
                                                    <li>
                                                        <strong>작성자 : </strong>
                                                        {{help.author.nickname}}
                                                    </li>
                                                    <li>
                                                        <strong>도움이 필요한 날짜 : </strong>
                                                        {{help.help_date}} {{help.help_day_week}}
                                                    </li>
                                                    <li>
                                                        <strong>도움이 필요한 시간 : </strong>
                                                        {{help.help_time}} 부터 약 {{help.hour}}시간
                                                    </li>
                                                    <li>
                                                        <strong>도움 요청 날짜 : </strong>
                                                        {{help.created_date}}
                                                    </li>
                                                </ul>
                                                {% if user.is_authenticated %}
                                                    {% if request.user == help.author and help.helper == None %}
                                                        <button class="btn btn-primary btn-xl" onclick = "location.href = '{% url 'donadona:resolution' help.id%}' "> 도움 해결 </button>
                                                    {% elif request.user != help.author and help.helper == None %}
                                                        <button class="btn btn-primary btn-xl" onclick = "location.href = '{% url 'donadona:help' help.id %}' "> 도움 주기 </button>
                                                    {% endif %}
                                                {% endif %}
                                                <button class="btn btn-primary btn-xl" data-bs-dismiss="modal" type="button">
                                                    <i class="fas fa-xmark me-1"></i>
                                                    닫기
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </section>
{% endblock %}

templates/donadona/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Masthead-->
        <header class="masthead">
            <div class="container">
                <div class="masthead-subheading"><font style="text-shadow:2px 2px 2px #000;">Welcome To DONADONA!</div>
                <div class="masthead-heading text-uppercase">도나도나에 오신 것을 환영합니다!</div>
                <div class="masthead-subheading">Welcome To DONADONA!</font></div>
                <a class="btn btn-primary btn-xl text-uppercase" href="{% url 'donadona:manual' %}"><font style="text-shadow:1px 1px 1px #000;">더 알아보기</font></a>
            </div>
        </header>
{% endblock %}

templates/donadona/mypage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Team-->
        <section class="page-section bg-light" id="team">
            <div class="container">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">내 정보 관리</h2>
                    <h3 class="section-subheading text-muted">Add, Check or Delete my information.</h3>
                </div>
                <div class="row">
                    <div class="col-lg-4">
                        <div class="team-member">
                        <a href="{% url 'donadona:info' %}">
                            <img class="mx-auto rounded-circle" src='{% static "assets/img/team/plus.png" %}' alt="..." /> </a>
                            <h4>도움정보 추가</h4>
                            <p class="text-muted">도움 가능한 날짜 · 지역 · 능력 정보 추가하기<br>
                            Add My Available Dates, Addresses, and Abilities.
                            </p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="team-member">
                        <a href="{% url 'donadona:myinfo' %}">
                            <img class="mx-auto rounded-circle" src='{% static "assets/img/team/check.png" %}' alt="..." /></a>
                            <h4>도움정보 확인</h4>
                            <p class="text-muted">도움 가능한 날짜 · 지역 · 능력 정보 확인하기<br>
                            Check My Available Dates, Addresses, and Abilities.
                            </p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="team-member">
                        <a href="{% url 'donadona:myhelp' %}">
                            <img class="mx-auto rounded-circle" src='{% static "assets/img/team/help.png" %}' alt="..." /></a>
                            <h4>나의 도움 이력</h4>
                            <p class="text-muted">나의 도움 이력 모아보기<br>
                            Check My DONADONA.
                            </p>
                        </div>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-lg-8 mx-auto text-center"><p class="large text-muted">
                     정보를 추가하고, 확인하고, 삭제하세요.<br>
                     정보를 정확히 입력하시면, 도움을 요청하거나 나눠줄 때 많은 도움이 됩니다.</p></div>
                </div>
            </div>
            <div class="text-center">
                <button class="btn btn-primary btn-xl" onclick = "location.href = '{% url 'account:logout' %}' "> 로그아웃 </button>
            </div>
        </section>
{% endblock %}

templates/donadona/mypage_info.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Services-->
        <section class="page-section" id="services">
            <div class="container">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">도움정보 확인</h2>
                    <h3 class="section-subheading text-muted">Check My Available Dates, Addresses, and Abilities.</h3>
                </div>
                <div class="row text-center">
                    <div class="col-md-4">
                        <h4 class="my-3">날짜</h4>
                        <p class="text-muted">가능한 요일과 시간대</p>
                        {% for time in times %}
                        <div class="card my-3">
                            <div class="card-body">
                                <div class="card-text">
                                {{time.day.day_week}}  {{time.start_time}}시 ~ {{time.end_time}}시
                                <button class="delete btn btn-sm btn-outline-danger" onclick = "location.href = '{% url 'donadona:myobj' 'time' time.id %}' " style="float: right;">
                                <input type="hidden" name="_method" value="DELETE"/> 삭제 </button>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <div class="col-md-4">
                        <h4 class="my-3">지역</h4>
                        <p class="text-muted">가까운 지역</p>
                        {% for address in addresses %}
                        <div class="card my-3">
                            <div class="card-body">
                                <div class="card-text">
                                {{address.address.city}} {{address.si_gun_gu}} {{address.addr_detail}}
                                <button class="delete btn btn-sm btn-outline-danger" onclick = "location.href = '{% url 'donadona:myobj' 'address' address.id %}' " style="float: right;">
                                <input type="hidden" name="_method" value="DELETE"/> 삭제 </button>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <div class="col-md-4">
                        <h4 class="my-3">능력</h4>
                        <p class="text-muted">할 수 있는 능력</p>
                        {% for ability in abilities %}
                        <div class="card my-3">
                            <div class="card-body">
                                <div class="card-text">
                                [ {{ability.ability.able_category}} ]  {{ability.able_detail}}
                                <button class="delete btn btn-sm btn-outline-danger" onclick = "location.href = '{% url 'donadona:myobj' 'ability' ability.id %}' " style="float: right;">
                                <input type="hidden" name="_method" value="DELETE"/> 삭제 </button>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        </div>
                </div>
            </div>
        </section>
{% endblock %}

templates/donadona/user_ability_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<br>
<div class="text-center"><h2>Update Abilities</h2></div>
<div class="container my-3">
<div class="d-flex justify-content-center">
    <form method="post" class="post-form" action="{% url 'donadona:ability' %}">
        {% csrf_token %}
       <p>
        <div class="form-group">
            <label for="able_category">할 수 있는 분야</label>
            <br> {{form.able_category}}
        </div></p>

        <p>
        <div class="form-group">
            <label for="able_detail"> 할 수 있는 상세 능력 </label>
            <div class="form-group">
                <input type="text" class="form-control" name="able_detail" id="able_detail"  placeholder="ex) 전구 교체"
                    value="{{form.able_detail.value|default_if_none:''}}">
            </div>
        </div></p>

        <button type="submit" class="btn btn-warning" >저장</button>
    </form>
</div>
</div>
{% endblock %}

templates/donadona/user_address_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<br>
<div class="text-center"><h2>Update Addresses</h2></div>
<div class="container my-3">
<div class="d-flex justify-content-center">
    <form method="post" class="post-form" action="{% url 'donadona:address' %}">
        {% csrf_token %}
       <p>
        <div class="form-group">
            <label for="city">도/특별시/광역시</label>
            <br> {{form.city}}
        </div></p>
        <p>
        <div class="form-group">
            <label for="si_gun_gu"> 시/군/구 </label>
            <div class="form-group">
                <input type="text" class="form-control" name="si_gun_gu" id="si_gun_gu"  placeholder="ex) 서대문구"
                    value="{{form.si_gun_gu.value|default_if_none:''}}">
            </div>
        </div>
        </p>

        <p>
        <div class="form-group">
            <label for="addr_detail"> 상세 주소 </label>
            <div class="form-group">
                <input type="text" class="form-control" name="addr_detail" id="addr_detail"  placeholder="ex) 대현동 11-1"
                    value="{{form.addr_detail.value|default_if_none:''}}">
            </div>
        </div>
        </p>
        <button type="submit" class="btn btn-warning" >저장</button>
    </form>
</div>
</div>
{% endblock %}

templates/donadona/user_info.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Team-->
        <section class="page-section bg-light" id="team">
            <div class="container">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">도움정보 추가</h2>
                    <h3 class="section-subheading text-muted">Add My Available Dates, Addresses, and Abilities.</h3>
                </div>
                <div class="row">
                    <div class="col-lg-4">
                        <div class="team-member">
                        <a href="{% url 'donadona:day' %}">
                            <img class="mx-auto rounded-circle" src='{% static "assets/img/team/1.jpg" %}' alt="..." /> </a>
                            <h4>날짜</h4>
                            <p class="text-muted">도움이 가능한 요일 및 시간 입력하기<br>
                            Update Available Dates, Addresses, and Abilities
                            </p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="team-member">
                        <a href="{% url 'donadona:address' %}">
                            <img class="mx-auto rounded-circle" src='{% static "assets/img/team/2.jpg" %}' alt="..." /> </a>
                            <h4>지역</h4>
                            <p class="text-muted">도움이 가능한 지역 및 주소 입력하기<br>
                            Update Available Dates, Addresses, and Abilities
                            </p>
                            </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="team-member">
                        <a href="{% url 'donadona:ability' %}">
                            <img class="mx-auto rounded-circle" src='{% static "assets/img/team/3.jpg" %}' alt="..." /></a>
                            <h4>능력</h4>
                            <p class="text-muted">도움이 가능한 능력 및 카테고리 입력하기<br>
                            Update Available Dates, Addresses, and Abilities
                            </p>
                            </div>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-lg-8 mx-auto text-center"><p class="large text-muted">
                     정보를 정확히 입력하시면, 도움을 요청하거나 나눠줄 때 많은 도움이 됩니다.</p></div>
                </div>
            </div>
        </section>
{% endblock %}