account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'account'

urlpatterns = [
    path('login', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('signup', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('donadona.urls')),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

donadona/urls.py
from django.urls import path
from . import views

app_name = 'donadona'

urlpatterns = [
    path('', views.main, name='main'),
    path('help/list', views.helpList, name='list'),  # 도움 목록
    path('help/request', views.helpRequest, name='request'),  # 도움 요청
    path('help/<int:help_id>', views.help, name='help'),  # 도움 주기
    path('resolution/<int:help_id>', views.resolution, name='resolution'),  # 도움 해결

    path('manual', views.manual, name='manual'),
    path('ranking', views.ranking, name='ranking'),

    path('mypage', views.mypage, name='mypage'),
    path('mypage/help/list', views.mypageHelp, name='myhelp'),
    path('mypage/info', views.mypageInfo, name='myinfo'),
    path('mypage/info/<str:obj>/<int:pk>', views.mypageObj, name='myobj'),

    path('info', views.userInfo, name='info'),
    path('info/day', views.userDay, name='day'),
    path('info/address', views.userAddress, name='address'),
    path('info/ability', views.userAbility, name='ability'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>DONADONA</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href='{% static "assets/icon.png" %}' />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href='{% static "css/styles.css" %}' rel="stylesheet" />
    </head>
    <body id="page-top">
<br>
<br>
<br>
{% include 'nav.html' %}
{% block content %}
{% endblock %}
<!-- Footer-->
        <footer class="footer py-4">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-4 text-lg-start">Copyright © DONADONA 2022 by WONPD</div>
                    <div class="col-lg-4 my-3 my-lg-0"></div>
                    <div class="col-lg-4 text-lg-end">
                        <a class="link-dark text-decoration-none me-3">CONTACT US</a>
                        <a class="link-dark text-decoration-none">010-7495-2331</a>
                    </div>
                </div>
            </div>
        </footer>
<!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src='{% static "js/scripts.js" %}'></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

templates/error.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <section class="page-section" id="about">
            <div class="container">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">ERROR</h2>
                    <h3 class="section-subheading text-muted">오류가 발생했습니다. 다시 시도해 주세요!</h3>
                </div>
            </div>
        </section>
{% endblock %}

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                   * {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/nav.html
{% load static %}
<!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="{% url 'donadona:main' %}"><font color = 'white'>DO</font>NADO<font color = 'white'>NA</font></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ms-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'donadona:list' %}">도움목록</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'donadona:request' %}">도움요청</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'donadona:ranking' %}">도움랭킹</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'donadona:manual' %}">이용방법</a></li>
                        {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'donadona:mypage' %}">{{user.nickname}}님</a></li>
                        {% else %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'account:login' %}">로그인</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>